### ISSUE TITLE
Does not run with Java 11

### ISSUE THREAD

**Issue by cowboy93** [Netflix/atlas#1004]
I followed Getting Started guide.
But, it causes error 

$ curl -LO https://github.com/Netflix/atlas/releases/download/v1.5.3/atlas-1.5.3-standalone.jar
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   616    0   616    0     0    582      0 --:--:--  0:00:01 --:--:--   583
100 27.7M  100 27.7M    0     0   114k      0  0:04:08  0:04:08 --:--:-- 85220
$ java -jar atlas-1.5.3-standalone.jar
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.netflix.spectator.impl.Config (file:/Users/smlee/.iep-launcher/atlas-1.5.3-standalone.jar/spectator-api-0.42.0.jar) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int)
WARNING: Please consider reporting this to the maintainers of com.netflix.spectator.impl.Config
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2019-03-07T10:56:11.636 ERROR [main] com.netflix.atlas.standalone.Main$: server failed to start, shutting down
java.lang.NoClassDefFoundError: javax/annotation/PostConstruct
	at com.netflix.iep.guice.AnnotationUtils.getPostConstruct(AnnotationUtils.java:38) ~[iep-guice-0.4.9.jar:0.4.9]
	at com.netflix.iep.guice.AnnotationUtils.invokePostConstruct(AnnotationUtils.java:57) ~[iep-guice-0.4.9.jar:0.4.9]
	at com.netflix.iep.guice.LifecycleModule$BindingListener.onProvision(LifecycleModule.java:42) ~[iep-guice-0.4.9.jar:0.4.9]
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:126) ~[guice-4.1.0.jar:?]
	at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:68) ~[guice-4.1.0.jar:?]
	at com.google.inject.internal.MembersInjectorImpl$1.call(MembersInjectorImpl.java:86) ~[guice-4.1.0.jar:?]
	at com.google.inject.internal.MembersInjectorImpl$1.call(MembersInjectorImpl.java:80) ~[guice-4.1.0.jar:?]
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085) ~[guice-4.1.0.jar:?]
	at com.google.inject.internal.MembersInjectorImpl.injectAndNotify(MembersInjectorImpl.java:80) ~[guice-4.1.0.jar:?]
	at com.google.inject.internal.Initializer$InjectableReference.get(Initializer.java:223) ~[guice-4.1.0.jar:?]
	at com.google.inject.internal.Initializer.injectAll(Initializer.java:132) ~[guice-4.1.0.jar:?]
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:174) ~[guice-4.1.0.jar:?]
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110) ~[guice-4.1.0.jar:?]
	at com.google.inject.Guice.createInjector(Guice.java:99) ~[guice-4.1.0.jar:?]
	at com.google.inject.Guice.createInjector(Guice.java:73) ~[guice-4.1.0.jar:?]
	at com.netflix.iep.guice.GuiceHelper.start(GuiceHelper.java:75) ~[iep-guice-0.4.9.jar:0.4.9]
	at com.netflix.atlas.standalone.Main$.start(Main.scala:84) ~[atlas-standalone_2.11-1.5.3-rc.1.jar:1.5.3-rc.1]
	at com.netflix.atlas.standalone.Main$.main(Main.scala:62) [atlas-standalone_2.11-1.5.3-rc.1.jar:1.5.3-rc.1]
	at com.netflix.atlas.standalone.Main.main(Main.scala) [atlas-standalone_2.11-1.5.3-rc.1.jar:1.5.3-rc.1]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at com.netflix.iep.launcher.Main.main(Main.java:143) [atlas-1.5.3-standalone.jar:?]
Caused by: java.lang.ClassNotFoundException: javax.annotation.PostConstruct
	at java.net.URLClassLoader.findClass(URLClassLoader.java:471) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
	at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:899) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	... 24 more
$ java -version
openjdk version "11.0.1" 2018-10-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.1+13)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.1+13, mixed mode)

**Comment by brharrington** [comment]
Should be fixed on latest 1.5.x snapshot, but because of some changes in the font engines in jdk11 the graphs look pretty poor unless it is customized enough via the config. That has been fixed in the 1.6.x RCs, but I haven't had time to back port it yet. I'll try to get a 1.5.4 release out later this week with the font changes and other jdk9+ patches.

**Comment by cowboy93** [comment]
Thank you for your fast reply ~ ! 👍

**Comment by brharrington** [comment]
Fixed in 1.5.4.
