### ISSUE TITLE
flakey test case for StreamOps

### ISSUE THREAD

**Issue by brharrington** [Netflix/atlas#1582]
```
com.netflix.atlas.pekko.StreamOpsSuite:
  + blocking queue, enqueued 0.045s
==> X com.netflix.atlas.pekko.StreamOpsSuite.blocking queue, droppedQueueFull  0.067s munit.ComparisonFailException: /home/runner/work/atlas/atlas/atlas-pekko/src/test/scala/com/netflix/atlas/pekko/StreamOpsSuite.scala:55
54:        val result = Utils.getTagValue(m.id(), "result")
55:        assertEquals(m.value(), expected.getOrElse(result, 0.0), result)
56:      }
droppedQueueFull
=> Obtained
5.0
=> Diff (- obtained, + expected)
-5.0
+4.0
    at munit.FunSuite.assertEquals(FunSuite.scala:11)
    at com.netflix.atlas.pekko.StreamOpsSuite.$anonfun$checkOfferedCounts$3(StreamOpsSuite.scala:55)
    at com.netflix.atlas.pekko.StreamOpsSuite.$anonfun$checkOfferedCounts$3$adapted(StreamOpsSuite.scala:53)
    at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:576)
    at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:574)
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1300)
    at com.netflix.atlas.pekko.StreamOpsSuite.checkOfferedCounts(StreamOpsSuite.scala:53)
    at com.netflix.atlas.pekko.StreamOpsSuite.$anonfun$new$3(StreamOpsSuite.scala:91)
```

**Comment by brharrington** [comment]
Haven't seen these failures in a long time.
