### ISSUE TITLE
build started failing with EOFException

### ISSUE THREAD

**Issue by brharrington** [Netflix/atlas#322]
https://travis-ci.org/Netflix/atlas/builds/113438027

```
Exception in thread "Thread-30" Exception in thread "Thread-26" java.io.EOFException
	at java.io.ObjectInputStream$BlockDataInputStream.peekByte(ObjectInputStream.java:2601)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1319)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371)
	at sbt.React.react(ForkTests.scala:114)
	at sbt.ForkTests$$anonfun$mainTestTask$1$Acceptor$2$.run(ForkTests.scala:74)
	at java.lang.Thread.run(Thread.java:745)
java.io.EOFException
	at java.io.ObjectInputStream$BlockDataInputStream.peekByte(ObjectInputStream.java:2601)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1319)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371)
	at org.scalatest.tools.Framework$ScalaTestRunner$Skeleton$1$React.react(Framework.scala:953)
	at org.scalatest.tools.Framework$ScalaTestRunner$Skeleton$1.run(Framework.scala:942)
	at java.lang.Thread.run(Thread.java:745)
```

Probably something changed with travis causing local hostname to stop resolving: 

http://stackoverflow.com/questions/33287424/strange-exception-in-sbt-test/33767077#33767077

**Comment by brharrington** [comment]
Appears to have been a transient error, tests now work again both with and without forking a new jvm for tests.
