### ISSUE TITLE
OutOfMemoryError when running tests

### ISSUE THREAD

**Issue by brharrington** [Netflix/atlas#466]
Occasionally seeing an out of memory error for Metaspace when running "sbt test" locally. So far haven't seen it in travis.

```
sbt appears to be exiting abnormally.
java.lang.OutOfMemoryError: Metaspace
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at sbt.State$.handleException(State.scala:242)
	at sbt.State$$anon$1.handleError(State.scala:205)
	at sbt.MainLoop$.next(MainLoop.scala:99)
	at sbt.MainLoop$.run(MainLoop.scala:89)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:68)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:63)
	at sbt.Using.apply(Using.scala:24)
	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:63)
	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:46)
	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:30)
	at sbt.MainLoop$.runLogged(MainLoop.scala:22)
	at sbt.StandardMain$.runManaged(Main.scala:57)
	at sbt.xMain.run(Main.scala:29)
	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
	at xsbt.boot.Launch$.run(Launch.scala:109)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
	at xsbt.boot.Launch$.launch(Launch.scala:117)
	at xsbt.boot.Launch$.apply(Launch.scala:18)
	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
	at xsbt.boot.Boot$.main(Boot.scala:17)
Error during sbt execution: java.lang.OutOfMemoryError: Metaspace
```

**Comment by skandragon** [comment]
Note that this happens on different tests, at different points.  I can reproduce this pretty reliably on my desktop.

**Comment by brharrington** [comment]
Cannot reproduce:

```
$ seq 1 10 | while read i; do echo "$(date) -- $i -- $(make > $i.txt 2>&1; echo $?)"; done
Wed Apr 19 13:16:52 PDT 2017 -- 1 -- 0
Wed Apr 19 13:20:32 PDT 2017 -- 2 -- 0
Wed Apr 19 13:24:11 PDT 2017 -- 3 -- 0
Wed Apr 19 13:27:51 PDT 2017 -- 4 -- 0
Wed Apr 19 13:31:25 PDT 2017 -- 5 -- 2
Wed Apr 19 13:38:59 PDT 2017 -- 6 -- 0
Wed Apr 19 13:42:31 PDT 2017 -- 7 -- 0
Wed Apr 19 13:46:03 PDT 2017 -- 8 -- 0
Wed Apr 19 13:49:36 PDT 2017 -- 9 -- 0
Wed Apr 19 13:53:04 PDT 2017 -- 10 -- 0
```

The one failure was a different issue:

```
$ cat 5.txt | grep error
[info] - read simple object with error
[info] - error image, 400x300
[info] - error image, 800x100
[info] - error diff image, 800x100
[error] Failed tests:
[error] 	com.netflix.atlas.poller.PollerManagerSuite
[error] (atlas-poller/test:test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 444 s, completed Apr 19, 2017 1:38:58 PM
```
