### ISSUE TITLE
Make Grapher serializable

### ISSUE THREAD

**Issue by jbrownuf07** [Netflix/atlas#940]
I'm using the SparkEvaluator in the atlas-eval-spark library and running into an exception that the class is not Serializable. The SparkEvaluator class contains a variable that is of type [com.netflix.atlas.eval.graph.Grapher,](https://github.com/Netflix/atlas/blob/master/atlas-eval/src/main/scala/com/netflix/atlas/eval/graph/Grapher.scala) which is currently not serializable and is blocking the SparkEvaluator class from being serializable. 

Here's a snippet of the code:

```val evaluator = new com.netflix.atlas.spark.SparkEvaluator(spark)

val ds_queries2 = spark
    .read.format("csv")
    .option("header", "true")
    .csv("s3://{bucket}/{file}")

val explode = com.netflix.atlas.spark.SparkEvaluator.explode _
val encoder = com.netflix.atlas.spark.SparkEvaluator.explodeEncoder

ds_queries2.rdd.map(row => {
    val job_id = row.getAs("job_id").toString()
    val score = row.getAs("score").toString.toDouble
    val baseline_uri = row.getAs("baseline").toString()
    val canary_uri = row.getAs("canary").toString()
    
    val ds_baseline = evaluator.eval(baseline_uri).flatMap(explode)(encoder)
    val ds_canary = evaluator.eval(canary_uri).flatMap(explode)(encoder)
    
    (job_id, score, baseline_uri, canary_uri, ds_baseline, ds_canary)
    }).take(1)
```

Here's a snippet of the stack-trace:

```Message: Task not serializable
StackTrace:   at org.apache.spark.util.ClosureCleaner$.org$apache$spark$util$ClosureCleaner$$clean(ClosureCleaner.scala:335)
  at org.apache.spark.util.ClosureCleaner$.clean(ClosureCleaner.scala:159)
  at org.apache.spark.SparkContext.clean(SparkContext.scala:2299)
  at org.apache.spark.rdd.RDD$$anonfun$map$1.apply(RDD.scala:376)
  at org.apache.spark.rdd.RDD$$anonfun$map$1.apply(RDD.scala:375)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
  at org.apache.spark.rdd.RDD.withScope(RDD.scala:368)
  at org.apache.spark.rdd.RDD.map(RDD.scala:375)
  ... 48 elided
Caused by: java.io.NotSerializableException: com.netflix.atlas.spark.SparkEvaluator
Serialization stack:
	- object not serializable (class: com.netflix.atlas.spark.SparkEvaluator, value: com.netflix.atlas.spark.SparkEvaluator@30edc597)
	- field (class: $iw, name: evaluator, type: class com.netflix.atlas.spark.SparkEvaluator)
	- object (class $iw, $iw@717f21bd)
	- field (class: $anonfun$2, name: $outer, type: class $iw)
	- object (class $anonfun$2, <function1>)
  at org.apache.spark.serializer.SerializationDebugger$.improveException(SerializationDebugger.scala:40)
  at org.apache.spark.serializer.JavaSerializationStream.writeObject(JavaSerializer.scala:46)
  at org.apache.spark.serializer.JavaSerializerInstance.serialize(JavaSerializer.scala:100)
  at org.apache.spark.util.ClosureCleaner$.ensureSerializable(ClosureCleaner.scala:342)
```

**Comment by zimmermatt** [comment]
I fixed this in the `SparkEvaluator` class directly. If we find other cases that require a fix here, we can take a look again at that point.
